"""Initial schema: companies, company_profiles, tenders, tender_chunks (+pgvector+HNSW).

Revision ID: 0001
Revises:
Create Date: 2026-06-22

Hand-written, not autogenerated. Alembic autogenerate misses: the pgvector
extension, HNSW index + cosine ops class, CHECK constraints, and
gen_random_uuid() defaults. Each of those is added explicitly below per the
database-designer skill.

Deliberate deviation from PRD §7 (documented here so it's discoverable):
`tender_chunks.company_id` is denormalized from `tenders.company_id`. This lets
vector retrievals filter `WHERE tender_id = $1 AND company_id = $2` without a
join — both a performance win and a defence against cross-tenant vector leakage
(rag-architect + api-security-reviewer skills). The cost is a write-time
denormalization (handled in the ingestor); the benefit is that every retrieval
is single-table and tenant-safe by construction.

The embedding dimension (768) is pinned by the embedding model choice
(gemini-embedding-001 @ output_dimensionality=768). Changing it is a full
re-embed of all tender_chunks rows, NOT a normal migration — flag and plan it.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- pgvector extension (idempotent) ---
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # pgcrypto gives us gen_random_uuid(); on PG13+ it's in core, but be safe.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto;")

    # --- companies ---
    op.create_table(
        "companies",
        sa.Column(
            "id",
            sa.String(36),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()::text"),
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("api_key_hash", sa.String(255), nullable=False, unique=True),
        sa.Column("monthly_doc_limit", sa.Integer, nullable=False, server_default="100"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )

    # --- company_profiles (1:1) ---
    op.create_table(
        "company_profiles",
        sa.Column(
            "company_id",
            sa.String(36),
            sa.ForeignKey("companies.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        # JSONB via raw type so we don't depend on dialect-specific imports.
        sa.Column("specialisations", sa.dialects.postgresql.JSONB, nullable=True),
        sa.Column("financial_capacity", sa.dialects.postgresql.JSONB, nullable=True),
        sa.Column("past_projects", sa.dialects.postgresql.JSONB, nullable=True),
        sa.Column("max_project_value", sa.Float, nullable=True),
    )

    # --- tenders ---
    op.create_table(
        "tenders",
        sa.Column(
            "id",
            sa.String(36),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()::text"),
        ),
        sa.Column(
            "company_id",
            sa.String(36),
            sa.ForeignKey("companies.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("filename", sa.String(512), nullable=False),
        sa.Column("storage_path", sa.Text, nullable=False),
        sa.Column("file_size_bytes", sa.Integer, nullable=False),
        sa.Column("page_count", sa.Integer, nullable=True),
        sa.Column("status", sa.String(32), nullable=False, server_default="uploading"),
        sa.Column("primary_language", sa.String(16), nullable=True),
        sa.Column("error_reason", sa.Text, nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.CheckConstraint(
            "status IN ('uploading', 'processing', 'ready', 'failed')",
            name="tenders_status_check",
        ),
        sa.CheckConstraint(
            "primary_language IS NULL OR primary_language IN ('ar', 'en', 'bilingual')",
            name="tenders_primary_language_check",
        ),
    )
    op.create_index(
        "ix_tenders_company_created",
        "tenders",
        ["company_id", sa.text("uploaded_at DESC")],
    )

    # --- tender_chunks ---
    # NOTE: `embedding vector(768)` — dimension pinned by gemini-embedding-001.
    op.execute(
        """
        CREATE TABLE tender_chunks (
            id                TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
            tender_id         TEXT NOT NULL REFERENCES tenders(id) ON DELETE CASCADE,
            company_id        TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
            chunk_index       INTEGER NOT NULL,
            content           TEXT NOT NULL,
            detected_language TEXT NOT NULL,
            page_number       INTEGER,
            embedding         vector(768) NOT NULL,
            CONSTRAINT tender_chunks_language_check
                CHECK (detected_language IN ('ar', 'en', 'mixed'))
        )
        """
    )
    # FK column indexes — Postgres does not auto-index FKs (database-designer skill).
    op.create_index(
        "ix_tender_chunks_tender_company",
        "tender_chunks",
        ["tender_id", "company_id"],
    )
    op.create_index("ix_tender_chunks_company", "tender_chunks", ["company_id"])
    # A tender's chunks are a strictly ordered set.
    op.create_index(
        "ux_tender_chunks_tender_index",
        "tender_chunks",
        ["tender_id", "chunk_index"],
        unique=True,
    )
    # HNSW ANN index — cosine ops class must match the .cosine_distance() operator
    # used in queries, or the planner can't use the index.
    op.execute(
        """
        CREATE INDEX ix_tender_chunks_embedding_hnsw
            ON tender_chunks USING hnsw (embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 64)
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_tender_chunks_embedding_hnsw")
    op.drop_index("ux_tender_chunks_tender_index", table_name="tender_chunks")
    op.drop_index("ix_tender_chunks_company", table_name="tender_chunks")
    op.drop_index("ix_tender_chunks_tender_company", table_name="tender_chunks")
    op.drop_table("tender_chunks")
    op.drop_index("ix_tenders_company_created", table_name="tenders")
    op.drop_table("tenders")
    op.drop_table("company_profiles")
    op.drop_table("companies")
    # Leave the pgvector extension in place — other databases on the cluster
    # may depend on it, and CREATE/DROP EXTENSION is not transactional anyway.
